project_id = "qtbhxnstepeybybvtaxk"

[functions.analise-triad3]
verify_jwt = false

[functions.processar-declaracao-irpf]
verify_jwt = true

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
